## Application
name: bidding_app
description: 'Application for bidders.'
publish_to: 'none'
version: 1.0.0+1

## Environment
environment:
  sdk: '>=3.2.6 <4.0.0'

## Dependencies
dependencies:
  flutter:
    sdk: flutter

  # Icon
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.6

  # Storage
  get_storage: ^2.1.1

  # Splash
  flutter_native_splash: ^2.3.10

  # Database
  firebase_core: ^2.25.0
  url_launcher: ^6.2.4
  intl: ^0.19.0
  http: ^1.2.0
  iconsax: ^0.0.8
  lottie: ^3.0.0
  logger: ^2.0.2+1
  firebase_auth: ^4.17.0
  smooth_page_indicator: ^1.1.0
  connectivity_plus: ^5.0.2

## Dev Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

## Rx
flutter:
  uses-material-design: true
  assets:
    # Images
    - assets/images/logo/
    - assets/images/menu/
    - assets/images/onboarding/

    - assets/images/social/

    # Icon
    - assets/icons/

    # Svg
    - assets/svgs/

    # Lottie
    - assets/lotties/

  # Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 800
